config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'favorites/create'
  get 'favorites/destroy'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'clients#index'
  resources :clients do
    resources :memos, only: [:create, :destroy]
    resources :checks, only: [:new, :index, :create, :destroy]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :client

  validates_uniqueness_of :client_id, scope: :user_id
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = current_user.favorites.create(client_id: params[:client_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @client = Client.find(params[:client_id])
    @favorite = current_user.favorites.find_by(client_id: @client.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if current_user.already_favorited?(client) %>
    <%= link_to client_favorites_path(client.id), method: :delete do %>
      <i class="fas fa-star"></i>
    <% end %>
  <% else %>
    <%= link_to client_favorites_path(client.id), method: :post do %>
      <i class="far fa-star"></i>
    <% end %>
<% end %>
  <%= client.favorites.count %>