config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'favorites/create'
  get 'favorites/destroy'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'clients#index'
  resources :clients do
    resources :memos, only: [:create, :destroy]
    resources :checks, only: [:new, :index, :create, :destroy]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show]
end

app/models/client.rb
class Client < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  belongs_to :user
  has_many :memos, dependent: :destroy
  has_many :checks, dependent: :destroy
  has_one_attached :image
  has_many :favorites, dependent: :destroy

  with_options format: { with: /\A[ぁ-んァ-ン一-龥]+\z/ } do
    validates :last_name, presence: true, length: { maximum: 10 }
    validates :first_name, allow_blank: true, length: { maximum: 10 }
  end
  with_options format: { with: /\A[ァ-ヶー－]+\z/ } do
    validates :last_name_kana, presence: true, length: { maximum: 10 }
    validates :first_name_kana, allow_blank: true, length: { maximum: 10 }
  end

  validates :company, length: { maximum: 15 }

  def self.search(search)
    if search != ''
      Client.where('last_name LIKE(?) OR first_name LIKE(?) OR last_name_kana LIKE(?) OR first_name_kana LIKE(?)',
                   "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      Client.all.order('created_at DESC')
    end
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:edit, :update, :show]
  before_action :move_to_index, except: [:index, :search]

  def index
    @clients = Client.includes(:user).order('created_at DESC')
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.create(client_params)
    if @client.valid?
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    client = Client.find(params[:id])
    client.destroy
    redirect_to root_path
  end

  def edit
  end

  def update
    @client.valid?
    if @client.update(client_params)
      redirect_to "/clients/#{@client.id}"
    else
      render :edit
    end
  end

  def show
    @memo = Memo.new
    @memos = @client.memos.includes(:user)
  end

  def search
    @clients = Client.search(params[:keyword])
  end

  private

  def client_params
    params.require(:client).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :company, :prefecture_id,
                                   :birthday, :image).merge(user_id: current_user.id)
  end

  def set_client
    @client = Client.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.html.erb
<div class="card", style="width: 14rem;">
<button type="button" class="btn btn-outline-secondary">
  <div>
    <%= render partial: 'favorites/favorite', locals: { client: client} %>
  <p class="card-text">作成者: <%= link_to client.user.name, user_path(client.user_id), class: :client_user %></p>
  </div>

  <% if client.image.attached? %>
  <%= image_tag client.image.variant(resize: '300x300'), class: 'card-img-top'  %>
  <% else %>
  <%= image_tag "noimage.png", :size =>'150x190', class: 'card-img-top' %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><%= link_to 'Profile', client_path(client.id), method: :get %></h5>
      <span class="name">
      <p class="card-text"><%= client.last_name %> <%= client.first_name %> 様</p>
      <p class="card-text"><%= client.last_name_kana %> <%= client.first_name_kana %> 様</p>
      <p class="card-text"><%= client.company %></p>
      </span>
  </div>
  </button>
</div>

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
      <div id="image-list"></div>
      <%= image_tag client.image.variant(resize: '300x300'), id: 'image' if client.image.present? %> 
    </label>
    <div>
      <label class="form-text">お名前(全角)</label>
      <span class="indispensable">必須</span>
        <%= f.text_field :last_name, placeholder: "last_name" %>
      <span class="indispensable">任意</span>
        <%= f.text_field :first_name, placeholder: "first_name" %>
    </div>
    <div>
      <label class="form-text">お名前カナ(全角)</label>
      <span class="indispensable">必須</span>
        <%= f.text_field :last_name_kana, placeholder: "last_name_kana" %>
      <span class="indispensable">任意</span>
        <%= f.text_field :first_name_kana, placeholder: "first_name_kana" %>
    </div>
    <div>
      <label class="form-text">会社名</label>
      <span class="any">任意</span>
        <%= f.text_field :company, placeholder: "company" %>
    </div>
    <div class="field">
        <label class="form-text">出身地</label>
        <span class="any">任意</span>
        <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name, {} %>
    </div>
      <label class="form-text">生年月日</label>
      <span class="any">任意</span>
      <div class='input-birth-wrap'>
        <%= raw sprintf(
                  f.date_select(
                    :birthday,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
      <%= f.submit('完了',class: 'btn btn-primary btn-lg my-1 mb-5 px-5')%>
<% end %>

app/views/clients/edit.html.erb
<div class="container text-center">
  <% if user_signed_in? && current_user.id == @client.user_id %>
    <div class="container">
      <h5><i class="far fa-address-card fa-2x"></i> 編集</h5>
      <%= render partial: "form", locals: { client: @client } %>
    </div>
  <% else %>
    <div class="container">
      <h5 class="m-0 text-center text-dark">カードの編集、削除、メモの削除、セルフチェックは作成者に限ります。</h5>
    </div>
  <% end %>
</div>

app/views/clients/index.html.erb
<% if user_signed_in? %>
   <div class="container text-center">
      <div class="item">
        <p>お客様の情報をカードに記録</p>
        <p>カードは社員同士で共有、メモ、ブックマーク</p>
        <p>社員はセルフチェックで、傾聴力が向上</p>
        <p>オンラインミーティングの話題を提供</p>
      </div>
      <ul class="more_list">
        <%= image_tag 'hands.png' , size: '50x50' %>
        <%= link_to "お客様カード新規作成", new_client_path, class: "btn btn-outline-primary my-2 my-sm-0", method: :get %>
      </ul>
    </div>
<% end %>
<div class="contents row">
  <% @clients.each do |client| %>
    <% if user_signed_in? %>
      <div class="more text-center">
        <ul class="more_list">
        <%= render partial: "client", locals: { client: client } %>
          <button type="button" class="btn btn-outline-primary">
            <%= link_to 'お客様メモ', client_path(client.id), method: :get %>
          </button>
        <% if user_signed_in? && current_user.id == client.user.id %>
          <button type="button" class="btn btn-outline-primary">
            <%= link_to 'セルフチェック', client_checks_path(client.id), method: :get %>
          </button>
        <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
</div>

  <% if user_signed_in? %>
      <%= image_tag 'present.png' , size: '30x30' %>
        <a href= "https://ja.wikipedia.org/wiki/Template:%E4%BB%8A%E6%97%A5%E3%81%AF%E4%BD%95%E3%81%AE%E6%97%A5" target="_blank"> ・今日は何の日？<a>
        <a href= "https://weathernews.jp/s/forecast/" target="_blank"> ・今日の天気は？<a>
        <a href= "https://jp.reuters.com/news/topNews" target="_blank"> ・トップニュース<a>
        <a href= "https://talkgacha.com/" target="_blank"> ・お困りの方はこちら<a>
  <% end %>

  <% if user_signed_in? %>
    <%= link_to(new_client_path, class: 'purchase-btn') do %>
    <span class='purchase-btn-text'>新規作成</span>
    <%= image_tag 'hands.png' , size: '90x90' ,class: "purchase-btn-icon" %>
    <% end %>
  <% else %>
    <%= link_to(new_user_session_path, class: 'purchase-btn') do %>
    <span class='purchase-btn-text'>新規作成</span>
    <%= image_tag 'hands.png' , size: '90x90' ,class: "purchase-btn-icon" %>
    <% end %>
  <% end %>

app/views/clients/new.html.erb
<div class="container text-center">
<div class="contents row">
  <% if user_signed_in? %>
    <div class="container">
      <h5><i class="far fa-address-card fa-2x"></i> 作成</h5>
      <%= render partial: "form", locals: { client: @client } %>
    </div>
  <% end %>
</div>

app/views/clients/search.html.erb
<div class="container text-center">
<h3>検索結果</h3>
<div class="contents row">
  <% @clients.each do |client| %>
    <% if user_signed_in? %>
      <div class="more">
        <ul class="more_list">
        <%= render partial: "client", locals: { client: client } %>
        <button type="button" class="btn btn-outline-primary">
          <%= link_to 'お客様詳細', client_path(client.id), method: :get %>
        </button>
        <button type="button" class="btn btn-outline-secondary">
          <%= link_to 'チェック一覧', client_checks_path(client.id), method: :get %>
        </button>
      </div>
    <% end %>
      </ul>
  <% end %>
</div>
</div>

app/views/clients/show.html.erb
<div class="clients">
  <div class="item">
  <% if user_signed_in? %>
    <div class="more text-center">
      <ul class="more_list">
      <h4><i class="far fa-address-card fa-2x"></i><%= @client.last_name %> <%= @client.first_name %> 様のカード</h4>
      <%= render partial: "client", locals: { client: @client } %>
      <% if user_signed_in? && current_user.id == @client.user.id %>
        <button type="button" class="btn btn-outline-primary">
          <%= link_to '編集', edit_client_path(@client.id), method: :get %>
        </button>
        <button type="button" class="btn btn-outline-secondary">
          <%= link_to '削除', client_path(@client.id), method: :delete %>
        </button>
      <% end %>
      </ul>
  </div>
</div>
 
    <div class="item text-left">
      <p>ご出身: <%= @client.prefecture.name %></p>
      <p>生年月日: <%= @client.birthday %></p>
      <div class="item">
      <p><%= @client.last_name %> 様の情報共有があればメモをお願いします。</p>
     </div>
      <%= form_with(model: [@client, @memo], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "メモする", rows: "2" %>
        <%= form.submit "メモ" %>
      <% end %>
    
        <% @memos.each.with_index(1) do |memo, idx| %>
          <p>
            <strong><%= memo.user.name %>のメモ <%= idx %>：</strong>
            <%= memo.text %>
          </p>
        <ul class="more_list">
        <% if user_signed_in? && current_user.id == memo.user.id %>
          <i class="fa fa-trash my-blue"></i> 
            <%= link_to 'メモ削除', client_memo_path(memo.client.id, memo.id), method: :delete %>
        <% end %>
        </ul>
        <% end %>
    </div>
  
    <% else %>
    <header class="bg-primary text-white">
      <div class="container text-center">
        <h1 class="text-dark">Welcome to <%= image_tag 'hands.png' , size: '50x50' %>Re:lations</h1>
          <p class="lead">※※※ カードの作成、メモには新規登録/ログインが必要です ※※※</p>
      </div>
    </header>
    <% end %>
</div>