config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'favorites/create'
  get 'favorites/destroy'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'clients#index'
  resources :clients do
    resources :memos, only: [:create, :destroy]
    resources :checks, only: [:new, :index, :create, :destroy]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show]
end

app/models/check.rb
class Check < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :smile
  belongs_to_active_hash :aizuchi
  belongs_to_active_hash :empathy
  belongs_to_active_hash :reaction
  belongs_to_active_hash :question

  belongs_to :user
  belongs_to :client

  validates :title, presence: true, length: { maximum: 10 }

  with_options numericality: { other_than: 0 } do
    validates :smile_id
    validates :aizuchi_id
    validates :empathy_id
    validates :reaction_id
    validates :question_id
  end
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  before_action :set_check, only: [:index, :new, :create, :destroy]
  before_action :move_to_index, except: :index

  def index
    @check = Client.new
    @checks = @client.checks.includes(:user).order('created_at DESC')
  end

  def new
    @check = Check.new
  end

  def create
    @check = Check.new(check_params)
    if @check.valid?
      @check.save
      redirect_to client_checks_path(@client.id)
    else
      render :new
    end
  end

  def destroy
    Check.find_by(id: params[:id], client_id: params[:client_id]).destroy
    redirect_to request.referer
  end

  private

  def check_params
    params.require(:check).permit(:title, :smile_id, :aizuchi_id, :empathy_id, :reaction_id, :question_id).merge(
      user_id: current_user.id, client_id: params[:client_id]
    )
  end

  def set_check
    @client = Client.find(params[:client_id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in? && current_user.id == @client.user_id
  end
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/views/checks/_check.html.erb
<div class="card" style="width: 14rem;">
<button type="button" class="btn btn-outline-secondary">
  <div class="card-body">
    <h5 class="card-title">Meeting</h5>
      <span class="name">
      <p><%= check.title %></p>
      <p><%= check.client.last_name %> 様</p>
      <p><%= check.created_at.strftime('%Y/%m/%d') %></p>
      <p>笑顔: <%= check.smile.name %></p>
      <p>相槌: <%= check.aizuchi.name %></p>
      <p>共感: <%= check.empathy.name %></p>
      <p>反応: <%= check.reaction.name %></p>
      <p>質問: <%= check.question.name %></p>
      </span>
  </div>
  </button>
</div>

app/views/checks/_form.html.erb
<%= form_with(model: [@client, check], local: true) do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
    <div>
      <label class="form-text">タイトル</label>
      <span class="indispensable">必須</span>
        <%= f.text_field :title, placeholder: "title" %>
    </div>
    <div class="field">
        <label class="form-text">笑顔で対応できましたか？</label>
        <span class="any">必須</span>
        <%= f.collection_select :smile_id, Smile.all, :id, :name, {} %>
    </div>
    <div class="field">
        <label class="form-text">相槌をして聞けましたか？</label>
        <span class="any">必須</span>
        <%= f.collection_select :aizuchi_id, Aizuchi.all, :id, :name, {} %>
    </div>
    <div class="field">
        <label class="form-text">共感を示せましたか？</label>
        <span class="any">必須</span>
        <%= f.collection_select :empathy_id, Empathy.all, :id, :name, {} %>
    </div>
    <div class="field">
        <label class="form-text">反応できましたか？</label>
        <span class="any">必須</span>
        <%= f.collection_select :reaction_id, Reaction.all, :id, :name, {} %>
    </div>
    <div class="field">
        <label class="form-text">質問できましたか？</label>
        <span class="any">必須</span>
        <%= f.collection_select :question_id, Question.all, :id, :name, {} %>
    </div>
      <%= f.submit('保存',class: 'btn btn-primary btn-lg my-1 mb-5 px-5')%>
<% end %>

app/views/checks/index.html.erb
<div class="clients">
  <div class="item">
<% if user_signed_in? && current_user.id == @client.user_id %>
    <div class="container text-center">
      <ul class="more_list">
        <%= render partial: "clients/client", locals: { client: @client } %>
      </ul>
    </div>

  </div>
  <div class="item">
    <p>自分自身の応対がどうだったか、<%= @client.last_name %> <%= @client.first_name %> 様への応対を振り返りましょう。</p>
    <p>応対した内容について振り返るのは、応対した内容をセルフチェックすることでより傾聴力を高めるためです。</p>
    <p>次の応対に向けて、どのように改善するかを考えましょう。</p>
    <i class="fa fa-thumbs-up fa-4x "></i> 
        <%= link_to "セルフチェック開始", new_client_check_path, class: "btn btn-outline-primary my-2 my-sm-0", method: :get %>
  </div>
</div>

<div class="contents row">
    <% @checks.each.with_index(1) do |check, idx| %>
    <div class="more">
      <p><strong><%= check.user.name %>のセルフチェック <%= idx %>：</strong></p>
      <%= render partial: "check", locals: { check: check } %>
    <i class="fa fa-trash my-blue"></i> 
      <%= link_to 'チェック削除', client_check_path(check.client.id, check.id), method: :delete %>
      </div>
    <% end %>
</div>
<% else %>
    <div class="container">
      <h5 class="m-0 text-center text-dark">カードの編集、削除、メモの削除、セルフチェックは作成者に限ります。</h5>
    </div>
<% end %>

app/views/checks/new.html.erb
<div class="container text-center">
<div class="contents row">
<% if user_signed_in? && current_user.id == @client.user.id %>
    <div class="container">

      <h5><i class="fa fa-edit fa-2x "></i> セルフチェック</h5>
      
      <%= render partial: "form", locals: { check: @check } %>
     </div>
  <% else %>
    <div class="container">
      <h5 class="m-0 text-center text-dark">カードの編集、削除、メモの削除、セルフチェックは作成者に限ります。</h5>
    </div>
<% end %>
</div>
</div>