config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'favorites/create'
  get 'favorites/destroy'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'clients#index'
  resources :clients do
    resources :memos, only: [:create, :destroy]
    resources :checks, only: [:new, :index, :create, :destroy]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show]
end

app/models/Empathy.rb
class Empathy < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '非常に悪い' },
    { id: 2, name: '悪い' },
    { id: 3, name: '普通' },
    { id: 4, name: '良い' },
    { id: 5, name: '非常に良い' }
  ]

  include ActiveHash::Associations
  has_many :checks
end

app/models/aizuchi.rb
class Aizuchi < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '非常に悪い' },
    { id: 2, name: '悪い' },
    { id: 3, name: '普通' },
    { id: 4, name: '良い' },
    { id: 5, name: '非常に良い' }
  ]

  include ActiveHash::Associations
  has_many :checks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check.rb
class Check < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :smile
  belongs_to_active_hash :aizuchi
  belongs_to_active_hash :empathy
  belongs_to_active_hash :reaction
  belongs_to_active_hash :question

  belongs_to :user
  belongs_to :client

  validates :title, presence: true, length: { maximum: 10 }

  with_options numericality: { other_than: 0 } do
    validates :smile_id
    validates :aizuchi_id
    validates :empathy_id
    validates :reaction_id
    validates :question_id
  end
end

app/models/client.rb
class Client < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  belongs_to :user
  has_many :memos, dependent: :destroy
  has_many :checks, dependent: :destroy
  has_one_attached :image
  has_many :favorites, dependent: :destroy

  with_options format: { with: /\A[ぁ-んァ-ン一-龥]+\z/ } do
    validates :last_name, presence: true, length: { maximum: 10 }
    validates :first_name, allow_blank: true, length: { maximum: 10 }
  end
  with_options format: { with: /\A[ァ-ヶー－]+\z/ } do
    validates :last_name_kana, presence: true, length: { maximum: 10 }
    validates :first_name_kana, allow_blank: true, length: { maximum: 10 }
  end

  validates :company, length: { maximum: 15 }

  def self.search(search)
    if search != ''
      Client.where('last_name LIKE(?) OR first_name LIKE(?) OR last_name_kana LIKE(?) OR first_name_kana LIKE(?)',
                   "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      Client.all.order('created_at DESC')
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :client

  validates_uniqueness_of :client_id, scope: :user_id
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  belongs_to :client

  validates :text, presence: true, length: { maximum: 100 }
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' }, { id: 1, name: '北海道' }, { id: 2, name: '青森県' },
    { id: 3, name: '岩手県' }, { id: 4, name: '宮城県' }, { id: 5, name: '秋田県' },
    { id: 6, name: '山形県' }, { id: 7, name: '福島県' }, { id: 8, name: '茨城県' },
    { id: 9, name: '栃木県' }, { id: 10, name: '群馬県' }, { id: 11, name: '埼玉県' },
    { id: 12, name: '千葉県' }, { id: 13, name: '東京都' }, { id: 14, name: '神奈川県' },
    { id: 15, name: '新潟県' }, { id: 16, name: '富山県' }, { id: 17, name: '石川県' },
    { id: 18, name: '福井県' }, { id: 19, name: '山梨県' }, { id: 20, name: '長野県' },
    { id: 21, name: '岐阜県' }, { id: 22, name: '静岡県' }, { id: 23, name: '愛知県' },
    { id: 24, name: '三重県' }, { id: 25, name: '滋賀県' }, { id: 26, name: '京都府' },
    { id: 27, name: '大阪府' }, { id: 28, name: '兵庫県' }, { id: 29, name: '奈良県' },
    { id: 30, name: '和歌山県' }, { id: 31, name: '鳥取県' }, { id: 32, name: '島根県' },
    { id: 33, name: '岡山県' }, { id: 34, name: '広島県' }, { id: 35, name: '山口県' },
    { id: 36, name: '徳島県' }, { id: 37, name: '香川県' }, { id: 38, name: '愛媛県' },
    { id: 39, name: '高知県' }, { id: 40, name: '福岡県' }, { id: 41, name: '佐賀県' },
    { id: 42, name: '長崎県' }, { id: 43, name: '熊本県' }, { id: 44, name: '大分県' },
    { id: 45, name: '宮崎県' }, { id: 46, name: '鹿児島県' }, { id: 47, name: '沖縄県' },
    { id: 48, name: '国外' }
  ]
  include ActiveHash::Associations
  has_many :clients
end

app/models/question.rb
class Question < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '非常に悪い' },
    { id: 2, name: '悪い' },
    { id: 3, name: '普通' },
    { id: 4, name: '良い' },
    { id: 5, name: '非常に良い' }
  ]

  include ActiveHash::Associations
  has_many :checks
end

app/models/reaction.rb
class Reaction < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '非常に悪い' },
    { id: 2, name: '悪い' },
    { id: 3, name: '普通' },
    { id: 4, name: '良い' },
    { id: 5, name: '非常に良い' }
  ]

  include ActiveHash::Associations
  has_many :checks
end

app/models/smile.rb
class Smile < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '非常に悪い' },
    { id: 2, name: '悪い' },
    { id: 3, name: '普通' },
    { id: 4, name: '良い' },
    { id: 5, name: '非常に良い' }
  ]

  include ActiveHash::Associations
  has_many :checks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :clients, dependent: :destroy
  has_many :memos, dependent: :destroy
  has_many :checks, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true, length: { maximum: 10 }

  def already_favorited?(client)
    favorites.exists?(client_id: client.id)
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def create
    memo = Memo.create(memo_params)
    redirect_to "/clients/#{memo.client.id}"
  end

  def destroy
    Memo.find_by(id: params[:id], client_id: params[:client_id]).destroy
    redirect_to request.referer
  end

  private

  def memo_params
    params.require(:memo).permit(:text).merge(user_id: current_user.id, client_id: params[:client_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def show
    @client = @user.clients
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Re:lations</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('hands.png') %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-dark bg-dark fixed-top" id="mainNav">
        <h2 class="display-5"><a href="/"><i class="far fa-address-card"></i> Re:lations</a></h2>
    <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <i class="fa fa-user my-blue"></i> <%= link_to current_user.name , "/users/#{current_user.id}", class: "user-nickname" %>
            <i class="fa fa-hand-paper my-blue"></i> <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          <%= form_with(url: search_clients_path, local: true, method: :get, class: "search-form") do |form| %>
            <%= form.text_field :keyword, placeholder: "お客様を検索", class: "search-input" %>
            <%= form.submit "検索", class: "btn btn-outline-primary my-2 my-sm-0" %>
          <% end %>
          </div>
    <% else %>
          <div class="user_nav grid-6">
          <i class="fa fa-address-card my-blue"></i><a class="text-primary" href="#about">About</a>
          <i class="fa fa-laptop my-blue"></i><a class="text-primary" href="#services">Issue</a>
          <i class="fa fa-street-view my-blue"></i><a class="text-primary" href="#contact">Why</a>
          <i class="far fa-thumbs-up my-blue"></i> <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          <i class="fa fa-hand-pointer my-blue"></i> <%= link_to "ログイン", new_user_session_path, class: "post" %>
        </div>
    <% end %>
      </nav>
    <header class="bg-primary text-white">
    <div class="container text-center">
      <p class="lead">お客様カード 記録アプリ</p>
      <h1 class="text-white">
      <% unless user_signed_in? %>
      Welcome to
      <% end %>
      <a href="/", class="text-white"><i class="far fa-address-card"></i>Re:lations</a></h1>
      <% unless user_signed_in? %>
      <p class="lead">リレーションズは、「対人関係で、幸せに気がつく」現代のビジネスカードです。</p>
      <% end %>
      </div>
      </header>
    
      <% unless user_signed_in? %>
      
      <div class="container text-center">
      <button type="button" class="btn btn-outline-secondary">
      <%= link_to "新規登録", new_user_registration_path, class: "post" %>
      </button>
      <button type="button" class="btn btn-outline-secondary">
      <%= link_to "ログイン", new_user_session_path, class: "post" %>
      </button>
      </div>
      <div class="container text-center">
      <button type="button" class="btn btn-outline-secondary">
      <%= link_to 'ゲストログイン(閲覧用)', users_guest_sign_in_path, method: :post %>
      </button>
        <p>ゲストログインからご覧いただけます。</p>
      </div>

      <% end %>
        <div class='container'>
          <%= yield %>
        </div>
    <% unless user_signed_in? %>
  <section id="about">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2><i class="fa fa-address-card fa-2x "></i> About</h2>
          <p class="lead my-blue">お客様の情報を社内で共有・振り返り</p>
          <ul>
            <p>お客様の情報をカードに記録することができます。</p>
            <p>お客様カードは社員同士で情報の共有、更新、ブックマークができます。</p>
            <p>社員は自分の対応を振り返ることで、傾聴力の向上を目指します。</p>
          </ul>
        </div>
      </div>
    </div>
  </section>

  <section id="services" class="bg-light">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2><i class="fa fa-laptop fa-2x "></i> Issue</h2>
          <p class="lead my-blue">オンラインによる対人関係の変化</p>
          <ul>
          <p>課題の背景は、ビジネスパーソンのリモート業務が増加傾向にあることです。</p>
          <p>リモートでの面会では、名刺交換の機会はありません。</p>
          <p>突発的な雑談の機会が減り、コミュニケーションも変化しています。</p>
          </ul>
        </div>
      </div>
    </div>
  </section>

  <section id="contact">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2><i class="fa fa-street-view fa-2x "></i> Why</h2>
          <p class="lead my-blue">人の全ての悩みは対人関係</p>
          <ul>
            <p>アドラー心理学では、「人間の悩みは、全て対人関係の悩みである」といわれています。</p>
            <p>対人関係を正しく構築できれば、この世界は、幸せで満ちていることに気がつくでしょう。</p>
          </ul>
        </div>
      </div>
    </div>
  </section>
    <% end %>
    <h5 class="display-5 text-center"><a href="/"><i class="far fa-address-card"></i>Re:lations TOP</a></h5>
    <footer class="py-1 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; 2020 Tatsuhiro Iwasaki</p>
    </div>
    </footer>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>